# Generated by Django 5.1.1 on 2024-09-17 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('character_type', models.CharField(choices=[('HU', 'Humain'), ('CH', 'Changelin')], default='HU', max_length=2)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Changeling',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.character')),
                ('seeming', models.CharField(choices=[('Fairest', 'Fairest'), ('Ogre', 'Ogre')], max_length=50)),
                ('kith', models.CharField(choices=[('Artist', 'Artist'), ('Soldier', 'Soldier')], max_length=50)),
            ],
            bases=('base.character',),
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.character')),
            ],
            bases=('base.character',),
        ),
    ]
